from algorithms.equal_algorithm import EqualAlgorithm
from algorithms.proportional_algorithm import ProportionalAlgorithm
from algorithms.page_fault_frequency import PageFaultFrequency
from algorithms.working_set import WorkingSet
